### PR TITLE
Fix a lot of stuff in present.py

### PR DESCRIPTION
**Pull request by linusheck**
See #5.

### CODE REVIEW

**Comment by linusheck** [comment]
Again, if this doesn't work for you, don't merge it :) I'm happy with this as my fork that I will use :D

**Comment by galatolofederico** [comment]
Hey i like the new state machine there seems to be two issues:
* the animations stop 1 frame before the actual last frame
* the pause is not working

I'll merge into a new branch and i'll try to fix those problems

**Comment by galatolofederico** [comment]
Also the loops seems to stop after the first iteration. For now i will leave it to you :sweat_smile:

**Comment by linusheck** [comment]
"the animations stop 1 frame before the actual last frame"
I think this happened before...
The state machine is not really new, I kinda changed yours, but I don't know if it completely makes sense yet.

**Comment by linusheck** [comment]
Thanks for the comments! I will look into them.

**Comment by linusheck** [comment]
Hey, I think I fixed pause & loops. The problem with the not really last frame is not mine, but this is so in manim exports in general. One solution would be showing the first frame on the next slide on WAIT (see commented code), but this fails if there is a clear() directly after pause() of course.

**Comment by galatolofederico** [comment]
Thanks it works fine! i just re added the `add_last_slide()` function in 1cc070db86656f31d69adfa12f4805121f7d2a66 because it was not working if the last slide was a loop

**Comment by galatolofederico** [comment]
Merged! i will merge the keybindings branch and i will tag a new version! thanks for your work!

**Comment by linusheck** [comment]
> Thanks it works fine! i just re added the `add_last_slide()` function in [1cc070d](https://github.com/galatolofederico/manim-presentation/commit/1cc070db86656f31d69adfa12f4805121f7d2a66) because it was not working if the last slide was a loop

This reintroduced the issue that you can't run scenes behind another, because the last slide doesn't have a corresponding video.

**Comment by linusheck** [comment]
Also, I thought the Wait() for one frame in pause() is a good idea. For which reason did you remove it? :D

**Comment by galatolofederico** [comment]
Because it is not needed with the `add_last_slide()`. Or this is was my understanding reading the code. The video of the last slide is the last animation of the current video

**Pull request merged**
